### ISSUE TITLE
Citation Error

### ISSUE THREAD

**Issue by shivgodhia** [expertailab/Is-BERT-self-attention-a-feature-selection-method#1]
Hi, I get a unicode error when I cite this using Latex. The issue lies here:

author    = {Andr{\'{e}}s Garc{\'{\i}}a{-}Silva and
               Jos{\'{e}} Manu{\'{e}}l G{\'{o}}mez{-}P{\'{e}}rez},

To fix it, use:

author    = {Andr{\'{e}}s Garc{\'{i}}a{-}Silva and
               Jos{\'{e}} Manu{\'{e}}l G{\'{o}}mez{-}P{\'{e}}rez},

I changed the i in Garcia from \i to I. Hopefully the resulting output is what you intended.

**Comment by andresgs77** [comment]
Hi, I fixed the BibTex entry by removing the accent marks in the authors. We usually don't include them in the citation. Thanks for pointing out this error.

**Comment by shivgodhia** [comment]
It was mostly fine before, just the i in Garcia had a typo. The other accents had no issues! I suggested the fix - if you prefer to have the accents it will work with my fix. Either way, cheers and thanks for sharing the interesting work you did!
